name: Convert Conf Files and Push to Repo

on:
  schedule:
    - cron: "0 1 * * *" # every day
  workflow_dispatch:

jobs:
  convert_conf_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: pip3 install glob2

    - name: Convert Conf Files
      env:
        CN_DNS: ${{ vars.CN_DNS }}
        THE_DNS: ${{ vars.THE_DNS }}
      run: python convert.py

    - name: Check for changes
      run: |
        git add converted/
        if ! git diff --cached --quiet; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          current_time=$(date +'%Y-%m-%d %H:%M:%S')
          git add .
          git commit -m "Convert conf files to txt - $current_time"
        else
          echo "No changes to commit."
        fi

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master

    - name: Create or update 'latest' release if not exists
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: "Latest Release"
        body: "Auto-updated release with the latest cn-dns.txt"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload cn-dns.txt to latest release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        files: converted/cn-dns.txt
        token: ${{ secrets.GITHUB_TOKEN }}
